from PyQt6 import QtCore, QtGui, QtWidgets
import sys



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 0, 1200, 700))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hBoxLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.playingfield = QtWidgets.QLabel(self.layoutWidget)
        self.playingfield.setObjectName("label")
        self.hBoxLayout.addWidget(self.playingfield)
        
        self.hBoxLayout.addLayout(self.gridLayout)

        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 99)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 13, 1, 50)
        spacerItem = QtWidgets.QSpacerItem(20, 418, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 6, 6, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["This", "is", "a", "test"])
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 5)
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_1.setStyleSheet("")
        self.label_1.setObjectName("label")
        self.gridLayout.addWidget(self.label_1, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 5, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.top9boxes = QtWidgets.QHBoxLayout()
        self.topterminal1 = QtWidgets.QLabel()
        self.topterminal1.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal1)
        self.topterminal2 = QtWidgets.QLabel()
        self.topterminal2.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal2)
        self.topterminal3 = QtWidgets.QLabel()
        self.topterminal3.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal3)
        self.topterminal4 = QtWidgets.QLabel()
        self.topterminal4.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal4)
        self.topterminal5 = QtWidgets.QLabel()
        self.topterminal5.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal5)
        self.topterminal6 = QtWidgets.QLabel()
        self.topterminal6.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal6)
        self.topterminal7 = QtWidgets.QLabel()
        self.topterminal7.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal7)
        self.topterminal8 = QtWidgets.QLabel()
        self.topterminal8.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal8)
        self.topterminal9 = QtWidgets.QLabel()
        self.topterminal9.setStyleSheet("background-color: red")
        self.top9boxes.addWidget(self.topterminal9)
        self.gridLayout.addLayout(self.top9boxes, 7, 0, 4, 64)

        self.middle9boxes = QtWidgets.QHBoxLayout()
        self.middleterminal1 = QtWidgets.QLabel()
        self.middleterminal1.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal1)
        self.middleterminal2 = QtWidgets.QLabel()
        self.middleterminal2.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal2)
        self.middleterminal3 = QtWidgets.QLabel()
        self.middleterminal3.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal3)
        self.middleterminal4 = QtWidgets.QLabel()
        self.middleterminal4.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal4)
        self.middleterminal5 = QtWidgets.QLabel()
        self.middleterminal5.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal5)
        self.middleterminal6 = QtWidgets.QLabel()
        self.middleterminal6.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal6)
        self.middleterminal7 = QtWidgets.QLabel()
        self.middleterminal7.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal7)
        self.middleterminal8 = QtWidgets.QLabel()
        self.middleterminal8.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal8)
        self.middleterminal9 = QtWidgets.QLabel()
        self.middleterminal9.setStyleSheet("background-color: red")
        self.middle9boxes.addWidget(self.middleterminal9)
        self.gridLayout.addLayout(self.middle9boxes, 12, 0, 4, 64)

        self.lower9boxes = QtWidgets.QHBoxLayout()
        self.lowerterminal1 = QtWidgets.QLabel()
        self.lowerterminal1.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal1)
        self.lowerterminal2 = QtWidgets.QLabel()
        self.lowerterminal2.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal2)
        self.lowerterminal3 = QtWidgets.QLabel()
        self.lowerterminal3.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal3)
        self.lowerterminal4 = QtWidgets.QLabel()
        self.lowerterminal4.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal4)
        self.lowerterminal5 = QtWidgets.QLabel()
        self.lowerterminal5.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal5)
        self.lowerterminal6 = QtWidgets.QLabel()
        self.lowerterminal6.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal6)
        self.lowerterminal7 = QtWidgets.QLabel()
        self.lowerterminal7.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal7)
        self.lowerterminal8 = QtWidgets.QLabel()
        self.lowerterminal8.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal8)
        self.lowerterminal9 = QtWidgets.QLabel()
        self.lowerterminal9.setStyleSheet("background-color: red")
        self.lower9boxes.addWidget(self.lowerterminal9)
        self.gridLayout.addLayout(self.lower9boxes, 17, 0, 4, 64)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "random"))
        self.label_2.setText(_translate("MainWindow", "info"))
        self.label_3.setText(_translate("MainWindow", "goes"))
        self.label_4.setText(_translate("MainWindow", "in"))
        self.label_5.setText(_translate("MainWindow", "these"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))